### ISSUE TITLE
Johns Hopkins

### ISSUE THREAD

**Issue by thejoby** [danielmurray/flatten#1]
Nice visualization. Also, hi!
https://github.com/danielmurray/flattenthevirus/blob/master/index.html#L77
"John Hopkins" -> "Johns Hopkins"

**Comment by danielmurray** [comment]
Lol, thanks, how'd you find this?

**Comment by danielmurray** [comment]
[fixed](https://github.com/danielmurray/flattenthevirus/commit/87afeca5d5390db97f7552ad18520c05b0048a86)

**Comment by danielmurray** [comment]
[fixed](https://github.com/danielmurray/flattenthevirus/commit/87afeca5d5390db97f7552ad18520c05b0048a86)

**Comment by thejoby** [comment]
Was looking at this: https://github.com/orb-framework/orb
Then clicked on your face, then looked at recent activity...then put the clever url in my browser.
Typical "dangers of being on the internet" type stuff. Have a nice day! :)

**Comment by danielmurray** [comment]
> Was looking at this: https://github.com/orb-framework/orb

May god have mercy on your soul
